#' @title iBayes
#'
#' @description
#' this function computes several features from posterior chains included in a list generated by the function Bunny interactive questions answered by the user.
#'
#' @param params A parameter file generated by the functions iCreateParam or CreateParam.
#' @param bunny A list generated by the function bunny containing all model specifications and posterior samples of inferences
#'
#' @return a list with the inferences computed for each trait
#' @import HDInterval
#' @import ggplot2
#' @import tidyr
#' @export
#'
#' @examples
#'
#'
#'


iBayes <- function(params, bunny) {

  cat(sprintf("%s", "\033[32m Enter the probability for the HPD interval, for example 0.95 (default is 0.95): \033[0m"))
  HPD <- as.numeric(readline())
  HPD <- ifelse(is.na(HPD), 0.95, HPD) # Default to 0.95

  cat(sprintf("%s", "\033[32m Do you want to calculate probability of the estimates being different from 0 (P0)? (Enter True=T or False=F, default is T): \033[0m"))
  P0 <- readline()
  P0 <- ifelse(tolower(P0) == "f", FALSE, TRUE)  # Default to TRUE if input is not "F"

  cat(sprintf("%s", "\033[32m Do you want to calculate a guaranteed value (K) for the estimates with a given probability? (Enter True=T or False=F, default is F): \033[0m"))
  K <- readline()
  K <- tolower(K) == "t"

  if(K) {
    cat(sprintf("%s", "\033[32mEnter the probability for the guaranteed value K, for example 0.80 (default is 0.80): \033[0m"))
    probK <- as.numeric(readline())
    probK <- ifelse(is.na(probK), 0.80, probK) #If K is TRUE default is 0.8
  } else {
    probK <- NA
  }

  cat(sprintf("%s", "\033[32mDo you want to calculate probability of contrasts being greater than a relevant value (PR) ? (Enter True=T or False=F, default is F): \033[0m"))
  PR <- readline()
  PR <- tolower(PR) == "t"

  cat(sprintf("%s", "\033[32mDo you want to calculate probability of similarity [-R, R] of contrasts (PS)? (Enter True=T or False=F, default is F): \033[0m"))
  PS <- readline()
  PS <- tolower(PS) == "t"

  if(PR || PS) {
    cat(sprintf("%s", "\033[32mEnter the R value(s), separated by commas if multiple traits (e.g., 0.1,0.2): \033[0m"))
    R_input <- readline()
    R <- as.numeric(unlist(strsplit(R_input, ",")))
  } else {
    R <- NA
  }

  cat(sprintf("%s", "\033[32m Do you want to save the inferences into a table? (Enter True=T or False=F, default is F): \033[0m"))
  SaveTable <- readline()
  SaveTable <- tolower(SaveTable) == "t"

  cat(sprintf("%s", "\033[32mDo you want to generate and save plots of constrats? (Enter True=T or False=F, default is F): \033[0m"))
  plot <- readline()
  plot <- tolower(plot) == "t"

  # Ensure that R has an entry for each trait if PR or PS are TRUE
  if((PR || PS) && (!is.vector(R) || length(R) != length(bunny))) {
    stop("When PR is TRUE, R must be a vector with one entry per trait.")
  }

  # Call the bayes function with the collected inputs
  results <- bayes(params, bunny, HPD, P0, K, probK, PR, R, PS, SaveTable, plot)

  return(results)
}
