#' @title iBayes
#'
#' @description
#' This function facilitates interactive computation of posterior chain analysis with Bayesian Statistics. It is an interactive counterpart to `Bayes`, leveraging a list generated by the `Bunny` function. It guides the user through a series of questions to define analysis parameters dynamically.
#'
#' @param params A parameter file generated by `iCreateParam` or `CreateParam`.
#' @param bunny A list produced by the `bunny` function, including all model specifications and posterior samples of inferences for different traits.
#'
#' @return Returns a list of computed inferences for each trait based on the user-defined criteria, including highest posterior density (HPD) intervals, probabilities of estimates being greater or different from specified values, and guaranteed values for a given probability.
#' @importFrom HDInterval hdi
#' @import ggplot2
#' @import tidyr
#' @importFrom ggdist stat_halfeye
#'
#' @examples
#' \dontrun{
#' # Example:
#' bayes_results <- iBayes(params=my_param_file, bunny=bunny_results)
#'}
#' @export

iBayes <- function(params, bunny) {
  cat(" iBayes Starting ... \n")
  cat(sprintf("%s", "\033[32mEnter the probability for the HPD interval, for example 0.95: \033[0m"))
  HPD <- as.numeric(readline())
  HPD <- ifelse(is.na(HPD), 0.95, HPD) # Default to 0.95

  #P0 set always TRUE
  # cat(sprintf("%s", "\033[32mDo you want to calculate probability of the posterior distribution being different from 0 (P0)? (Enter Yes=Y or No=N): \033[0m"))
  # P0 <- readline()
  # P0 <- ifelse(tolower(P0) == "n", FALSE, TRUE)  # Default to TRUE if input is not "F"
  P0<-TRUE

  cat(sprintf("%s", "\033[32mDo you want to calculate a guaranteed value (K) for the posterior distribution with a given probability? (Enter Yes=Y or No=N): \033[0m"))
  K <- readline()
  K <- tolower(K) == "y"

  if(K) {
    cat(sprintf("%s", "\033[32mEnter the probability for the guaranteed value K, for example 0.80: \033[0m"))
    probK <- as.numeric(readline())
    probK <- ifelse(is.na(probK), 0.80, probK) #If K is TRUE default is 0.8
  } else {
    probK <- NA
  }

  cat(sprintf("%s", "\033[32mDo you want to calculate probability of contrasts being greater than a relevant value (PR) ? (Enter Yes=Y or No=N): \033[0m"))
  PR <- readline()
  PR <- tolower(PR) == "y"

  cat(sprintf("%s", "\033[32mDo you want to calculate probability of similarity [-R, R] of contrasts (PS)? (Enter Yes=Y or No=N): \033[0m"))
  PS <- readline()
  PS <- tolower(PS) == "y"

  if(PR || PS) {
    cat(sprintf("%s", "\033[32mEnter the R value(s), separated by commas if multiple traits (e.g., 0.1,0.2): \033[0m"))
    R_input <- readline()
    R <- as.numeric(unlist(strsplit(R_input, ",")))
  } else {
    R <- NA
  }

  cat(sprintf("%s", "\033[32mDo you want to save the inferences into a table? (Enter Yes=Y or No=N): \033[0m"))
  SaveTable <- readline()
  SaveTable <- tolower(SaveTable) == "y"

  cat(sprintf("%s", "\033[32mDo you want to generate and save plots of contrasts? (Enter Yes=Y or No=N):  \033[0m"))
  plot <- readline()
  plot <- tolower(plot) == "y"

  # Ensure that R has an entry for each trait if PR or PS are TRUE
  if((PR || PS) && (!is.vector(R) || length(R) != length(bunny))) {
    stop("When PR is TRUE, R must be a vector with one entry per trait.")
  }

  # Call the Bayes function with the collected inputs
  results <- Bayes(params, bunny, HPD, P0, K, probK, PR, R, PS, SaveTable, plot)

  return(results)
}
